apiVersion: "k8s.cni.cncf.io/v1"

kind: NetworkAttachmentDefinition

metadata:

  name: net-vlan501

  annotations:

    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/bridge-ens3f7

spec:

  config: '{

    "cniVersion": "0.3.1",

    "name": "net-vlan501", 

    "plugins": [

      {

        "type": "cnv-bridge", 

        "bridge": "bridge-ens3f7", 

        "vlan": 501

      },

      {

        "type": "cnv-tuning" 

      }

    ]

  }'
