apiVersion: nmstate.io/v1beta1

kind: NodeNetworkConfigurationPolicy

metadata:

  name: bridge-ens3f7 

spec:

  nodeSelector: 

    node-role.kubernetes.io/worker: "" 

  desiredState:

    interfaces:

      - name: bridge-ens3f7

        description: Linux bridge with ens3f7 as a port 

        type: linux-bridge

        state: up

        ipv4:

          dhcp: true

          enabled: true

        bridge:

          options:

            stp:

              enabled: false

          port:

            - name: ens3f7
