apiVersion: "k8s.cni.cncf.io/v1"

kind: NetworkAttachmentDefinition

metadata:

  name: bridge-11

  annotations:

    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/bridge-ens3f0

spec:

  config: '{

    "cniVersion": "0.3.1",

    "name": "bridge-11", 

    "plugins": [

      {

        "type": "cnv-bridge", 

        "bridge": "bridge-ens3f0", 

        "vlan": 11

      },

      {

        "type": "cnv-tuning" 

      }

    ]

  }'
