apiVersion: v1

kind: ConfigMap

metadata:

  name: cluster-monitoring-config

  namespace: openshift-monitoring

data:

  config.yaml: |

    prometheusK8s:

      volumeClaimTemplate:

       spec:

         storageClassName: ocs-storagecluster-ceph-rbd

         volumeMode: Filesystem

         resources:

           requests:

             storage: 40Gi

    alertmanagerMain:

      volumeClaimTemplate:

       spec:

         storageClassName: ocs-storagecluster-ceph-rbd

         volumeMode: Filesystem

         resources:

           requests:

             storage: 40Gi

    thanosRuler:

      volumeClaimTemplate:

       spec:

         storageClassName: ocs-storagecluster-ceph-rbd

         volumeMode: Filesystem

         resources:

           requests:

             storage: 40Gi
---             
apiVersion: v1

kind: ConfigMap

metadata:

  name: user-workload-monitoring-config

  namespace: openshift-user-workload-monitoring

data:

  config.yaml: |

    prometheus:

      volumeClaimTemplate:

        spec:

          storageClassName: ocs-storagecluster-ceph-rbd

          resources:

            requests:

              storage: 20Gi

    thanosRuler:

      volumeClaimTemplate:

       spec:

         storageClassName: ocs-storagecluster-ceph-rbd

         volumeMode: Filesystem

         resources:

           requests:

             storage: 20Gi

