apiVersion: v1
items:
- apiVersion: imageregistry.operator.openshift.io/v1
  kind: Config
  metadata:
    creationTimestamp: "2021-10-15T10:53:40Z"
    finalizers:
    - imageregistry.operator.openshift.io/finalizer
    generation: 3
    name: cluster
    resourceVersion: "3932572"
    uid: 504108d2-4ded-4439-b039-0a47f4d7f9f1
  spec:
    httpSecret: 8e9967f1be70a4504502ec5af5aabdef4820c777f736bc57de463b1cb745beb98916e17c5e1e58f63c0eb79f44bc482dfbd2da587b63ff79c5bc1a78123e9717
    logLevel: Normal
    managementState: Managed
    observedConfig: null
    operatorLogLevel: Normal
    proxy: {}
    replicas: 1
    requests:
      read:
        maxWaitInQueue: 0s
      write:
        maxWaitInQueue: 0s
    rolloutStrategy: RollingUpdate
    storage: {}
    unsupportedConfigOverrides: null
  status:
    conditions:
    - lastTransitionTime: "2021-10-15T10:53:40Z"
      reason: AsExpected
      status: "False"
      type: ImageConfigControllerDegraded
    - lastTransitionTime: "2021-10-15T10:53:40Z"
      reason: AsExpected
      status: "False"
      type: ImageRegistryCertificatesControllerDegraded
    - lastTransitionTime: "2021-10-15T10:55:09Z"
      message: The daemon set node-ca has available replicas
      reason: AsExpected
      status: "True"
      type: NodeCADaemonAvailable
    - lastTransitionTime: "2021-10-15T10:53:40Z"
      reason: AsExpected
      status: "False"
      type: NodeCADaemonControllerDegraded
    - lastTransitionTime: "2021-10-18T10:27:26Z"
      message: 'Unable to apply resources: storage backend not configured'
      reason: Error
      status: "False"
      type: Progressing
    - lastTransitionTime: "2021-10-18T10:27:30Z"
      message: 'Error: storage backend not configured'
      reason: StorageNotConfigured
      status: "False"
      type: Available
    - lastTransitionTime: "2021-10-18T10:27:30Z"
      message: 'Error: storage backend not configured'
      reason: StorageNotConfigured
      status: "True"
      type: Degraded
    - lastTransitionTime: "2021-10-18T10:27:30Z"
      status: "False"
      type: Removed
    generations:
    - group: apps
      hash: ""
      lastGeneration: 0
      name: node-ca
      namespace: openshift-image-registry
      resource: daemonsets
    observedGeneration: 3
    readyReplicas: 0
    storage: {}
    storageManaged: false
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
